services:
  mongodb:
    image: mongo:7
    container_name: noteedit_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: noteedit
    volumes:
      - mongo_noteedit:/data/db

volumes:
  mongo_noteedit:
